name: xAuth
main: com.cypherx.xauth.xAuth
version: 1.2.5
description: Allows players to register and maintain an account while the server is in offline-mode.
author: CypherX

commands:
    register:
        description: Register your player name
        usage: /register <password>
    login:
        aliases: [l]
        description: Authenticate yourself
        usage: /login <password>
    changepw:
        description: Change your or another players password
        usage: /changepw [player] <password>
    unregister:
        description: Remove a players registration
        usage: /unregister <player>
    authreload:
        description: Reload the account, configuration, and string files
        usage: /authreload
    toggle:
        description: Toggle various commands on/off
        usage: /toggle <reg|changepw|autosave|filter|blankname|verifyip|strike|forcereg>
    logout:
        description: End a players session and force them to re-authenticate
        usage: /logout [player]