name: xAuth
version: 2.0.2
description: Offline-mode Authentication
author: CypherX
website: https://github.com/CypherX/xAuth

main: com.cypherx.xauth.xAuth

commands:
  register:
    description: Register your player with the supplied password.
    usage: /<command> <password> [email]
  login:
    description: Authenticate yourself as the owner of this player.
    aliases: [l]
    usage: /<command> <password>
  logout:
    description: Manually end your login session.
    usage: /<command>
  changepw:
    description: Change your password.
    aliases: [changepassword, changepass, cpw]
    usage: /<command> <old password> <new password>
  xauth:
    description: Access all xAuth admin commands.
    aliases: [x]
    usage: |
           /<command> register <player> <password> [email]
           /<command> changepw <player> <new password>
           /<command> logout <player>
           /<command> unregister <player>
           /<command> location set|remove [global]
           /<command> reload

permissions:
  xauth.register:
    description: Allows players/groups to register when new registrations are disabled.
    default: true
  xauth.admin.*:
    description: Grants access to all xAuth admin commands
    children:
        xauth.admin.register: true
        xauth.admin.changepw: true
        xauth.admin.logout: true
        xauth.admin.unregister: true
        xauth.admin.location: true
  xauth.admin.register:
    description: Allows you to register other players
    default: op
  xauth.admin.changepw:
    description: Allows changing of other players passwords
    default: op
  xauth.admin.logout:
    description: Allows you to end a players session
    default: op
  xauth.admin.unregister:
    description: Remove a players registration
    default: op
  xauth.admin.location:
    description: Set/remove the current world or global teleport location
    default: op