name: xAuth
version: 2.0-dev
description: Offline-mode Authentication
author: CypherX
#website: http://forums.bukkit.org/threads/MyPlugin.31337/

main: com.cypherx.xauth.xAuth
database: false
#depend: [NewFire, FlameWire]

commands:
  register:
    description: Register your player with the supplied password.
    usage: /<command> <password> [email]
  login:
    description: Authenticate yourself as the owner of this player.
    aliases: [l]
    usage: /<command> <password>
  logout:
    description: Manually end your login session.
    usage: /<command>
  changepw:
    description: Change your password.
    aliases: [changepassword, changepass, cpw]
    usage: /<command> <old password> <new password>
  xauth:
    description: Access all xAuth admin commands.
    aliases: [x]
    usage: |
           /<command> register <player> <password> [email]
           /<command> changepw <player> <new password>
           /<command> logout <player>
           /<command> unregister <player>
           /<command> strike list|clear [ip]
           /<command> location set|remove [global]
           /<command> reload

permissions:
#  inferno.*:
#    description: Gives access to all Inferno commands
#    children:
#      inferno.flagrate: true
#      inferno.burningdeaths: true
#      inferno.burningdeaths.others: true
  xauth.register:
    description: Allows players/groups to register when new registrations are disabled.
    default: true
#  inferno.burningdeaths:
#    description: Allows you to see how many times you have burned to death
#    default: true
#  inferno.burningdeaths.others:
#    description: Allows you to see how many times others have burned to death
#    default: op
#    children:
#      inferno.burningdeaths: true