session:
    verifyip: false
    timeout: 3600
notify:
    limit: 5
login:
    strikes:
        amount: 5
        enabled: true
        action: kick
registration:
    enabled: true
    forced: true
password:
    complexity:
        uppercase: false
        enabled: false
        symbols: false
        numbers: false
        lowercase: false
    min-length: 4
filter:
    allowed: abcdefghijklmnopqrstuvwxyz0123456789_- ()[]{}
    enabled: true
    block-blankname: true
misc:
    allow-changepw: true
    allowed-cmds:
    - /register
    - /login
    autosave: true
