name: xAuth
main: com.cypherx.xauth.xAuth
version: 1.1.4

commands:
    register:
        description: Register your player name
        usage: /register <password>
    login:
        description: Authenticate yourself
        usage: /login <password>
    changepw:
        description: Change your or another players password
        usage: |
                /changepw <password>
                /changepw <player> <password>
    unregister:
        description: Remove a players registration
        usage: /unregister <player>
    authreload:
        description: Reload the account, configuration, and string files
        usage: /authreload
    toggle:
        description: Toggle various commands on/off
        usage: |
                /toggle reg
                /toggle changepw
                /toggle autosave